# 02G — Protein domains

In [1]:
import pandas as pd
import numpy as np
import re
from pathlib import Path
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from scipy.stats import fisher_exact, chi2_contingency, mannwhitneyu, kruskal, spearmanr, ks_2samp, entropy, norm
from IPython.display import display

PROCESSED = Path('../../data/processed')
df = pd.read_csv(PROCESSED / 'DMD_variants_annotated.csv')

print('Loaded:', PROCESSED / 'DMD_variants_annotated.csv')
print('Shape:', df.shape)

Loaded: ../../data/processed/DMD_variants_annotated.csv
Shape: (11308, 30)

In [2]:
import sys
from pathlib import Path

PROJECT_ROOT = None
for rel in ('../..', '..', '.'):
    cand = (Path.cwd() / rel).resolve()
    if (cand / 'src' / 'utils.py').exists():
        PROJECT_ROOT = cand
        break
if PROJECT_ROOT is None:
    raise FileNotFoundError('project root with src/utils.py not found')
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.utils import (
    add_consistency_flags,
    bh_adjust,
    chi2_table,
    ecdf_xy,
    fisher_bool,
    frame_mismatch,
    kruskal_group,
    mann_whitney_bool,
    mut_cons_mismatch,
    odds_ratio_ci,
    path_cons_mismatch,
    prepare_eda_dataframe,
    spearman_xy,
)

d = prepare_eda_dataframe(df)

print('Prepared shape:', d.shape)

Prepared shape: (11308, 59)

## 1. 📊 domain counts

In [3]:
dom_counts = d['domain_clean'].value_counts().head(30).reset_index()
dom_counts.columns = ['domain', 'count']
display(dom_counts)
fig = px.bar(dom_counts, x='domain', y='count', title='Domain counts')
fig.update_xaxes(tickangle=-45)
fig.show()

                       domain  count
0       Interaction with SYNM    243
1                  Spectrin 4    148
2                  Spectrin 2    146
3                  Spectrin 5    144
4   Calponin-homology (CH2) 2    140
5                  Spectrin 1    132
6                  Spectrin 6    128
7                  Spectrin 3    126
8                 Spectrin 12    120
9                 Spectrin 15    119
10                 Spectrin 7    119
11  Calponin-homology (CH1) 1    113
12                Spectrin 14    112
13                 Spectrin 9    111
14                Spectrin 23    108
15                Spectrin 13    107
16                Spectrin 11    103
17                Spectrin 16    103
18                 Spectrin 8     94
19                Spectrin 22     87
20                Spectrin 24     84
21                Spectrin 21     82
22                Spectrin 18     78
23                Spectrin 19     78
24                Spectrin 17     77
25                Spectrin 20     72
26                 Disordered     65
27                Spectrin 10     47
28         ZZ-type;degenerate     46
29              Actin-binding     39

## 2. 📊 domain pathogenic stacked 🛡

In [4]:
top = d['domain_clean'].value_counts().head(20).index
tmp = d[d['domain_clean'].isin(top)][['domain_clean', 'pathogenic']]
fig = px.histogram(tmp, x='domain_clean', color='pathogenic', barmode='stack', title='Domain x pathogenic')
fig.update_xaxes(tickangle=-45)
fig.show()

## 3. 📊 domain pathogenic fraction 🛡

In [5]:
tbl = d.groupby('domain_clean').agg(pathogenic_fraction=('pathogenic', 'mean'), n=('var_id', 'size')).reset_index().sort_values('n', ascending=False).head(25)
display(tbl)
fig = px.bar(tbl, x='domain_clean', y='pathogenic_fraction', hover_data=['n'], title='Domain pathogenic fraction')
fig.update_xaxes(tickangle=-45)
fig.show()

                 domain_clean  pathogenic_fraction    n
6       Interaction with SYNM             0.415638  243
25                 Spectrin 4             0.351351  148
18                 Spectrin 2             0.308219  146
26                 Spectrin 5             0.291667  144
4   Calponin-homology (CH2) 2             0.314286  140
7                  Spectrin 1             0.287879  132
27                 Spectrin 6             0.273438  128
24                 Spectrin 3             0.301587  126
10                Spectrin 12             0.283333  120
13                Spectrin 15             0.302521  119
28                 Spectrin 7             0.294118  119
3   Calponin-homology (CH1) 1             0.283186  113
12                Spectrin 14             0.321429  112
30                 Spectrin 9             0.198198  111
22                Spectrin 23             0.342593  108
11                Spectrin 13             0.242991  107
14                Spectrin 16             0.330097  103
9                 Spectrin 11             0.398058  103
29                 Spectrin 8             0.329787   94
21                Spectrin 22             0.356322   87
23                Spectrin 24             0.238095   84
20                Spectrin 21             0.243902   82
17                Spectrin 19             0.358974   78
16                Spectrin 18             0.320513   78
15                Spectrin 17             0.415584   77

## 4. 🧪 Fisher domain vs rest ⭐

In [6]:
top = d['domain_clean'].value_counts()[lambda s: s >= 20].index
rows = []
for dom in top:
    tmp = d[['domain_clean', 'pathogenic']].dropna().copy()
    tmp['is_domain'] = tmp['domain_clean'].eq(dom)
    tab, odds, p, ci = fisher_bool(tmp, 'is_domain', 'pathogenic')
    rows.append({'domain': dom, 'odds_ratio': odds, 'p_value': p, 'or_ci_low': ci[1], 'or_ci_high': ci[2]})
res = pd.DataFrame(rows).sort_values('p_value')
display(res.head(40))

                       domain  odds_ratio   p_value  or_ci_low  or_ci_high
26                 Disordered    0.257897  0.000122   0.117300    0.567015
0       Interaction with SYNM    1.611527  0.000546   1.234122    2.104345
30             Binds to SNTB1    3.498062  0.000673   1.691468    7.234211
13                 Spectrin 9    0.528477  0.006665   0.329390    0.847897
29              Actin-binding    2.320477  0.013803   1.232913    4.367394
24                Spectrin 17    1.567942  0.061956   0.990311    2.482494
16                Spectrin 11    1.460036  0.067127   0.976946    2.182008
15                Spectrin 13    0.691660  0.112730   0.441804    1.082818
20                Spectrin 24    0.674658  0.152563   0.406048    1.120960
21                Spectrin 21    0.697075  0.185491   0.418743    1.160410
1                  Spectrin 4    1.190420  0.320105   0.842207    1.682602
6                  Spectrin 6    0.813801  0.332350   0.547676    1.209240
23                Spectrin 19    1.226857  0.389619   0.767736    1.960543
19                Spectrin 22    1.213098  0.413091   0.777187    1.893503
27                Spectrin 10    0.744234  0.431632   0.384680    1.439859
8                 Spectrin 12    0.856860  0.484460   0.571932    1.283735
28         ZZ-type;degenerate    0.766478  0.523114   0.395211    1.486517
14                Spectrin 23    1.141005  0.527989   0.761332    1.710019
11  Calponin-homology (CH1) 1    0.856507  0.536147   0.564903    1.298636
5                  Spectrin 1    0.876442  0.565903   0.596744    1.287237
3                  Spectrin 5    0.893009  0.582530   0.618474    1.289408
10                 Spectrin 7    0.904848  0.687774   0.605585    1.351997
18                 Spectrin 8    1.074784  0.736277   0.694547    1.663185
17                Spectrin 16    1.076571  0.746621   0.709037    1.634617
9                 Spectrin 15    0.943329  0.840771   0.633311    1.405106
7                  Spectrin 3    0.938871  0.844846   0.636952    1.383901
25                Spectrin 20    1.023599  0.898634   0.620153    1.689509
22                Spectrin 18    1.028811  0.902170   0.635654    1.665138
12                Spectrin 14    1.033626  0.917533   0.690260    1.547797
2                  Spectrin 2    0.969742  0.927408   0.676917    1.389238
4   Calponin-homology (CH2) 2    0.998919  1.000000   0.693528    1.438788

## 5. 📋 domain OR + q-values ⭐

In [7]:
top = d['domain_clean'].value_counts()[lambda s: s >= 20].index
rows = []
for dom in top:
    tmp = d[['domain_clean', 'pathogenic']].dropna().copy()
    tmp['is_domain'] = tmp['domain_clean'].eq(dom)
    tab, odds, p, ci = fisher_bool(tmp, 'is_domain', 'pathogenic')
    rows.append({'domain': dom, 'odds_ratio': odds, 'p_value': p, 'or_ci_low': ci[1], 'or_ci_high': ci[2]})
res = pd.DataFrame(rows)
res['q_value'] = bh_adjust(res['p_value'].values)
res = res.sort_values('q_value')
display(res.head(40))

,domain,odds_ratio,p_value,or_ci_low,or_ci_high,q_value
26,Disordered,0.257897,0.000122,0.117300,0.567015,0.003789
0,Interaction with SYNM,1.611527,0.000546,1.234122,2.104345,0.006952
30,Binds to SNTB1,3.498062,0.000673,1.691468,7.234211,0.006952
13,Spectrin 9,0.528477,0.006665,0.329390,0.847897,0.051651
29,Actin-binding,2.320477,0.013803,1.232913,4.367394,0.085578
16,Spectrin 11,1.460036,0.067127,0.976946,2.182008,0.297276
24,Spectrin 17,1.567942,0.061956,0.990311,2.482494,0.297276
15,Spectrin 13,0.691660,0.112730,0.441804,1.082818,0.436828
20,Spectrin 24,0.674658,0.152563,0.406048,1.120960,0.525494
21,Spectrin 21,0.697075,0.185491,0.418743,1.160410,0.575022
1,Spectrin 4,1.190420,0.320105,0.842207,1.682602,0.858572
6,Spectrin 6,0.813801,0.332350,0.547676,1.209240,0.858572
8,Spectrin 12,0.856860,0.484460,0.571932,1.283735,0.859925
28,ZZ-type;degenerate,0.766478,0.523114,0.395211,1.486517,0.859925
27,Spectrin 10,0.744234,0.431632,0.384680,1.439859,0.859925
23,Spectrin 19,1.226857,0.389619,0.767736,1.960543,0.859925
19,Spectrin 22,1.213098,0.413091,0.777187,1.893503,0.859925
5,Spectrin 1,0.876442,0.565903,0.596744,1.287237,0.859925
14,Spectrin 23,1.141005,0.527989,0.761332,1.710019,0.859925
11,Calponin-homology (CH1) 1,0.856507,0.536147,0.564903,1.298636,0.859925
3,Spectrin 5,0.893009,0.582530,0.618474,1.289408,0.859925
17,Spectrin 16,1.076571,0.746621,0.709037,1.634617,0.958321
18,Spectrin 8,1.074784,0.736277,0.694547,1.663185,0.958321
7,Spectrin 3,0.938871,0.844846,0.636952,1.383901,0.958321
22,Spectrin 18,1.028811,0.902170,0.635654,1.665138,0.958321
12,Spectrin 14,1.033626,0.917533,0.690260,1.547797,0.958321
25,Spectrin 20,1.023599,0.898634,0.620153,1.689509,0.958321
10,Spectrin 7,0.904848,0.687774,0.605585,1.351997,0.958321
9,Spectrin 15,0.943329,0.840771,0.633311,1.405106,0.958321
2,Spectrin 2,0.969742,0.927408,0.676917,1.389238,0.958321
4,Calponin-homology (CH2) 2,0.998919,1.000000,0.693528,1.438788,1.000000

## 6. 📊 domain vs phenotype

In [8]:
top = d['domain_clean'].value_counts().head(15).index
tmp = d[d['domain_clean'].isin(top)]
heat = pd.crosstab(tmp['domain_clean'], tmp['phenotype'])
fig = px.imshow(heat, aspect='auto', color_continuous_scale='Blues', title='Domain vs phenotype')
fig.show()

## 7. 🧪 χ² domain ~ phenotype

In [9]:
tmp = d[d['domain_clean'].isin(d['domain_clean'].value_counts()[lambda s: s >= 20].index)]
tab, chi2, p, dof = chi2_table(tmp, 'domain_clean', 'phenotype')
display(tab.head(30))
display(pd.Series({'chi2': chi2, 'dof': dof, 'p_value': p}).to_frame('value'))

phenotype                  BMD  DMD
domain_clean
Actin-binding                3   26
Binds to SNTB1               3   23
Calponin-homology (CH1) 1   10   87
Calponin-homology (CH2) 2   14  105
Disordered                   5   50
Interaction with SYNM       26  178
Spectrin 1                   7  104
Spectrin 10                  2   40
Spectrin 11                  8   82
Spectrin 12                 15   90
Spectrin 13                 11   87
Spectrin 14                  6   95
Spectrin 15                 12   86
Spectrin 16                  6   84
Spectrin 17                  7   60
Spectrin 18                  5   58
Spectrin 19                  4   69
Spectrin 2                  17  109
Spectrin 20                  8   55
Spectrin 21                  6   66
Spectrin 22                  8   69
Spectrin 23                  6   93
Spectrin 24                  6   73
Spectrin 3                  14   94
Spectrin 4                  12  116
Spectrin 5                  10  121
Spectrin 6                   7  106
Spectrin 7                   9   98
Spectrin 8                   6   70
Spectrin 9                  10   86

             value
chi2     24.643724
dof      30.000000
p_value   0.742154

## 8. 📊 domain vs mutation_type

In [10]:
top = d['domain_clean'].value_counts().head(15).index
tmp = d[d['domain_clean'].isin(top)]
heat = pd.crosstab(tmp['domain_clean'], tmp['mutation_type'])
fig = px.imshow(heat, aspect='auto', color_continuous_scale='Viridis', title='Domain vs mutation_type')
fig.show()

## 9. 🧪 χ² domain ~ mutation

In [11]:
tmp = d[d['domain_clean'].isin(d['domain_clean'].value_counts()[lambda s: s >= 20].index)]
tab, chi2, p, dof = chi2_table(tmp, 'domain_clean', 'mutation_type')
display(tab.head(30))
display(pd.Series({'chi2': chi2, 'dof': dof, 'p_value': p}).to_frame('value'))

mutation_type,frameshift,large_deletion,missense,nonsense,splice
domain_clean,,,,,
Actin-binding,15,0,17,4,3
Binds to SNTB1,12,0,11,7,1
Calponin-homology (CH1) 1,13,0,70,18,12
Calponin-homology (CH2) 2,14,0,86,31,7
Disordered,3,0,52,6,2
Interaction with SYNM,47,0,125,58,9
Spectrin 1,10,0,80,32,6
Spectrin 10,1,0,33,12,1
Spectrin 11,16,0,52,29,6
Spectrin 12,9,0,76,30,4
Spectrin 13,10,0,70,21,4
Spectrin 14,11,0,72,27,1
Spectrin 15,9,0,75,32,2
Spectrin 16,13,0,59,28,3
Spectrin 17,11,0,42,22,2
Spectrin 18,8,0,47,20,3
Spectrin 19,12,0,43,21,2
Spectrin 2,15,0,93,27,10
Spectrin 20,6,0,44,20,2
Spectrin 21,4,0,57,20,1
Spectrin 22,11,0,50,22,4
Spectrin 23,9,0,66,29,4
Spectrin 24,8,0,60,14,1
Spectrin 3,13,1,80,24,7
Spectrin 4,15,1,87,40,5
Spectrin 5,14,0,91,33,4
Spectrin 6,8,0,87,32,0
Spectrin 7,14,0,73,26,6
Spectrin 8,11,0,58,21,4
Spectrin 9,6,0,81,18,6

                value
chi2     2.233882e+02
dof      1.200000e+02
p_value  3.172493e-08

## 10. 📊 rod vs binding domain ⭐

In [12]:
tmp = d[['domain_clean', 'pathogenic']].copy()
tmp['domain_class'] = np.where(tmp['domain_clean'].str.contains('spectrin', case=False, na=False), 'rod', np.where(tmp['domain_clean'].str.contains('interaction|actin|binding|ch1|ch2|ww|cysteine', case=False, regex=True, na=False), 'binding', 'other'))
cls = tmp[tmp['domain_class'].isin(['rod', 'binding'])]
tbl = cls.groupby('domain_class').agg(pathogenic_fraction=('pathogenic', 'mean'), n=('pathogenic', 'size')).reset_index()
display(tbl)
fig = px.bar(tbl, x='domain_class', y='pathogenic_fraction', hover_data=['n'], title='Rod vs binding domain pathogenic fraction')
fig.show()

  domain_class  pathogenic_fraction     n
0      binding             0.366171   538
1          rod             0.306139  2525

## 11. 🧪 Fisher rod vs binding ⭐

In [13]:
tmp = d[['domain_clean', 'pathogenic']].copy()
tmp['domain_class'] = np.where(tmp['domain_clean'].str.contains('spectrin', case=False, na=False), 'rod', np.where(tmp['domain_clean'].str.contains('interaction|actin|binding|ch1|ch2|ww|cysteine', case=False, regex=True, na=False), 'binding', 'other'))
cls = tmp[tmp['domain_class'].isin(['rod', 'binding'])].copy()
cls['is_rod'] = cls['domain_class'].eq('rod')
tab, odds, p, ci = fisher_bool(cls, 'is_rod', 'pathogenic')
display(tab)
display(pd.Series({'odds_ratio_rod_vs_binding': odds, 'p_value': p, 'or_ci_low': ci[1], 'or_ci_high': ci[2]}).to_frame('value'))

pathogenic  False  True
is_rod
False         341    197
True         1752    773

                              value
odds_ratio_rod_vs_binding  0.763719
p_value                    0.007901
or_ci_low                  0.628570
or_ci_high                 0.927926

## 12. 📊 domain treemap

In [14]:
tbl = d.groupby('domain_clean').agg(n=('var_id', 'size'), pathogenic_fraction=('pathogenic', 'mean')).reset_index().sort_values('n', ascending=False).head(40)
fig = px.treemap(tbl, path=['domain_clean'], values='n', color='pathogenic_fraction', title='Domain treemap')
fig.show()

## 13. 📊 domain size vs pathogenic fraction

In [15]:
tmp = d.dropna(subset=['domain_clean', 'aa_pos_num']).copy()
span = tmp.groupby('domain_clean').agg(start=('aa_pos_num', 'min'), end=('aa_pos_num', 'max'), pathogenic_fraction=('pathogenic', 'mean'), n=('var_id', 'size')).reset_index()
span['domain_size_est'] = span['end'] - span['start'] + 1
span = span[span['n'] >= 10]
display(span.sort_values('n', ascending=False).head(30))
fig = px.scatter(span, x='domain_size_est', y='pathogenic_fraction', size='n', text='domain_clean', title='Domain size vs pathogenic fraction')
fig.show()

,domain_clean,start,end,pathogenic_fraction,n,domain_size_est
6,Interaction with SYNM,1415.0,3408.0,0.415638,243,1994.0
25,Spectrin 4,720.0,828.0,0.351351,148,109.0
18,Spectrin 2,448.0,555.0,0.308219,146,108.0
26,Spectrin 5,830.0,934.0,0.291667,144,105.0
4,Calponin-homology (CH2) 2,134.0,239.0,0.314286,140,106.0
7,Spectrin 1,340.0,447.0,0.287879,132,108.0
27,Spectrin 6,943.0,1045.0,0.273438,128,103.0
24,Spectrin 3,560.0,665.0,0.301587,126,106.0
10,Spectrin 12,1574.0,1676.0,0.283333,120,103.0
28,Spectrin 7,1048.0,1154.0,0.294118,119,107.0
13,Spectrin 15,1877.0,1978.0,0.302521,119,102.0
3,Calponin-homology (CH1) 1,16.0,119.0,0.283186,113,104.0
12,Spectrin 14,1779.0,1874.0,0.321429,112,96.0
30,Spectrin 9,1267.0,1365.0,0.198198,111,99.0
22,Spectrin 23,2809.0,2930.0,0.342593,108,122.0
11,Spectrin 13,1681.0,1778.0,0.242991,107,98.0
14,Spectrin 16,1993.0,2100.0,0.330097,103,108.0
9,Spectrin 11,1468.0,1567.0,0.398058,103,100.0
29,Spectrin 8,1157.0,1263.0,0.329787,94,107.0
21,Spectrin 22,2690.0,2801.0,0.356322,87,112.0
23,Spectrin 24,2936.0,3038.0,0.238095,84,103.0
20,Spectrin 21,2581.0,2686.0,0.243902,82,106.0
16,Spectrin 18,2211.0,2318.0,0.320513,78,108.0
17,Spectrin 19,2319.0,2422.0,0.358974,78,104.0
15,Spectrin 17,2106.0,2208.0,0.415584,77,103.0
19,Spectrin 20,2476.0,2574.0,0.319444,72,99.0
5,Disordered,3529.0,3685.0,0.107692,65,157.0
8,Spectrin 10,1368.0,1414.0,0.255319,47,47.0
32,ZZ-type;degenerate,3309.0,3363.0,0.260870,46,55.0
1,Actin-binding,3.0,132.0,0.512821,39,130.0

## 14. 🧪 Spearman domain size vs pathogenic 📖

In [16]:
tmp = d.dropna(subset=['domain_clean', 'aa_pos_num']).copy()
span = tmp.groupby('domain_clean').agg(start=('aa_pos_num', 'min'), end=('aa_pos_num', 'max'), pathogenic_fraction=('pathogenic', 'mean'), n=('var_id', 'size')).reset_index()
span['domain_size_est'] = span['end'] - span['start'] + 1
span = span[span['n'] >= 10]
_, rho, p = spearman_xy(span, 'domain_size_est', 'pathogenic_fraction')
display(pd.Series({'n_domains': len(span), 'spearman_rho': rho, 'p_value': p}).to_frame('value'))

                  value
n_domains     31.000000
spearman_rho   0.275752
p_value        0.133223

## 15. 📊 domain entropy 📖

In [17]:
p = d['domain_clean'].value_counts(normalize=True)
ent = entropy(p.values, base=2)
display(pd.Series({'n_domains': int(p.shape[0]), 'entropy_bits': float(ent)}).to_frame('value'))

                  value
n_domains     33.000000
entropy_bits   4.852372

## 16. 📊 domain positional ordering

In [18]:
tmp = d.dropna(subset=['domain_clean', 'aa_pos_num']).copy()
order_tbl = tmp.groupby('domain_clean').agg(median_aa=('aa_pos_num', 'median'), n=('var_id', 'size')).reset_index().sort_values('median_aa')
fig = px.bar(order_tbl, x='domain_clean', y='median_aa', hover_data=['n'], title='Domain positional ordering by median aa')
fig.update_xaxes(tickangle=-45)
fig.show()